#!/usr/bin/env bash

set -e

if [ "$#" -eq 0 ]; then
    CONFIG="install.conf.yaml"
else
    if [ "$#" -ne 1 ]; then
        echo "Too many arguments!"
    fi
    CONFIG="$1"
fi
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
