#!/usr/bin/env bash

temp_config=$(mktemp)
echo "Writing temp dotbot config to ${temp_config}, with shell directives removed"
echo ""
./write_link_only_dotbot_config.py $temp_config
./install $temp_config

