#!/usr/bin/env bash
# TODO set dotfiles up to copy this rather than link, and rename
# to indicate it is for *deployment-specific* environment variables
# (if not obvious enough from their usual purpose...)

# used by some of my data acquisition / analysis tools
export HONG_NAS="/local/storage"

# Used this in place of HONG_NAS on my home computer
#export HONG2P_DATA="$HOME/2p_data"

# Checked before path derived from above when determining where a fly directory is.
# All data in fly directory must be copied here because there is currently no more
# granularity.
export HONG2P_FAST_DATA="$HOME/2p_data"

export OLFACTOMETER_HARDWARE_DIR="$HOME/src/tom_olfactometer_configs/hardware"
export OLFACTOMETER_DEFAULT_HARDWARE="dual_manifold2"

