#! /usr/bin/python3

from pathlib import Path

if __name__ == '__main__':
    # TODO delete / comment
    log_file = Path.home() / 'nautilus_test.log'

    cwd = Path.cwd()
    #log_file.write_text(f'{cwd=}\n')

    for f in cwd.glob('*'):
        # TODO this excludes dirs, right?
        if not f.is_file():
            continue

        if f.is_symlink():
            continue

        prefix = f'{f.parent.name}_'
        new_name = f.parent / f'{prefix}{f.name}'

        if f.name.startswith(prefix):
            without_prefix = f.name[len(prefix):]
            new_name = f.parent / without_prefix
            f.rename(new_name)

        # TODO delete/comment
        #log_file.write_text(f'renaming {f} -> {new_name}\n')
